from __future__ import annotations

from dataclasses import dataclass
from difflib import unified_diff
import hashlib
from pathlib import Path
import re
from typing import Any

from .model import ManagedState
from .nix_generator import generate_module
from .storage import serialize_state
from .system_inspector import SystemInspection, inspect_system


_DEFAULT_MODULE_HEADER = """# Generated by Nix Control Manager. DO NOT EDIT BY HAND.
# This stable entrypoint imports the settings managed by the application.
"""
_SAFE_IMPORTS_LINE = re.compile(r"(?m)^(?P<indent>[ \t]*)imports\s*=\s*\[\s*(?:#.*)?$")


@dataclass(frozen=True, slots=True)
class PlannedFileChange:
    path: Path
    relative_path: str
    action: str
    reason: str
    previous: str
    candidate: str
    diff: str

    @staticmethod
    def _digest(content: str) -> str:
        return hashlib.sha256(content.encode("utf-8")).hexdigest()

    @property
    def previous_sha256(self) -> str | None:
        return self._digest(self.previous) if self.action == "modify" else None

    @property
    def candidate_sha256(self) -> str:
        return self._digest(self.candidate)

    def to_mapping(self) -> dict[str, Any]:
        return {
            "path": str(self.path),
            "relativePath": self.relative_path,
            "action": self.action,
            "reason": self.reason,
            "diff": self.diff,
            "candidate": self.candidate,
            "previousSha256": self.previous_sha256,
            "candidateSha256": self.candidate_sha256,
        }


@dataclass(frozen=True, slots=True)
class AdoptionPlan:
    status: str
    safe_to_apply: bool
    inspection: SystemInspection
    changes: tuple[PlannedFileChange, ...]
    warnings: tuple[str, ...]
    git_root: Path | None = None
    files_requiring_staging: tuple[str, ...] = ()

    @property
    def combined_diff(self) -> str:
        return "\n".join(change.diff.rstrip() for change in self.changes if change.diff).rstrip() + (
            "\n" if any(change.diff for change in self.changes) else ""
        )

    def to_mapping(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "safeToApply": self.safe_to_apply,
            "changes": [change.to_mapping() for change in self.changes],
            "combinedDiff": self.combined_diff,
            "warnings": list(self.warnings),
            "git": {
                "root": str(self.git_root) if self.git_root else None,
                "filesRequiringStaging": list(self.files_requiring_staging),
            },
            "system": self.inspection.to_mapping(),
        }


def _relative_label(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root)).replace("\\", "/")
    except ValueError:
        return path.name


def _file_change(root: Path, path: Path, candidate: str, reason: str) -> PlannedFileChange | None:
    try:
        previous = path.read_bytes().decode("utf-8") if path.is_file() else ""
    except (OSError, UnicodeDecodeError):
        previous = ""
    if previous == candidate:
        return None
    relative = _relative_label(root, path)
    action = "modify" if path.exists() else "create"
    diff = "".join(
        unified_diff(
            previous.splitlines(keepends=True),
            candidate.splitlines(keepends=True),
            fromfile=relative,
            tofile=f"{relative} (candidate)",
        )
    )
    return PlannedFileChange(
        path=path,
        relative_path=relative,
        action=action,
        reason=reason,
        previous=previous,
        candidate=candidate,
        diff=diff,
    )


def _standard_default_module(output_name: str) -> str:
    return (
        f"{_DEFAULT_MODULE_HEADER}\n"
        "{ ... }:\n\n"
        "{\n"
        "  imports = [\n"
        f"    ./{output_name}\n"
        "  ];\n"
        "}\n"
    )


def _managed_output_from_default(default_path: Path) -> Path | None:
    if not default_path.is_file():
        return None
    try:
        content = default_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    for name in ("managed.nix", "packages.nix"):
        if re.search(rf"(?<![A-Za-z0-9_'-])\./{re.escape(name)}(?![A-Za-z0-9_'-])", content):
            return default_path.parent / name
    return None


def _insert_managed_import(configuration_path: Path) -> tuple[str | None, str | None]:
    try:
        content = configuration_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as error:
        return None, f"Cannot read {configuration_path}: {error}"
    match = _SAFE_IMPORTS_LINE.search(content)
    if not match:
        return None, (
            "The configuration does not contain a simple multiline `imports = [` block; "
            "automatic insertion is intentionally disabled."
        )
    insertion = f"{match.group('indent')}  ./ncm # managed by Nix Control Manager\n"
    return content[: match.end()] + "\n" + insertion + content[match.end() + 1 :], None


def _find_git_root(start: Path) -> Path | None:
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate
    return None


def _finalize_plan(
    *,
    status: str,
    inspection: SystemInspection,
    changes: list[PlannedFileChange],
    warnings: list[str],
) -> AdoptionPlan:
    git_root = _find_git_root(inspection.config_root)
    staging: list[str] = []
    if inspection.configuration_mode == "flake" and git_root:
        for change in changes:
            if change.action == "create":
                try:
                    staging.append(str(change.path.relative_to(git_root)).replace("\\", "/"))
                except ValueError:
                    staging.append(str(change.path))
        if staging:
            warnings.append(
                "New files must be staged before a Git-backed flake can evaluate them."
            )
    safe = status in {"ready", "migration-ready", "no-changes"}
    return AdoptionPlan(
        status=status,
        safe_to_apply=safe,
        inspection=inspection,
        changes=tuple(changes),
        warnings=tuple(dict.fromkeys(warnings)),
        git_root=git_root,
        files_requiring_staging=tuple(staging),
    )


def plan_adoption(config_root: Path = Path("/etc/nixos")) -> AdoptionPlan:
    inspection = inspect_system(config_root)
    root = inspection.config_root
    warnings = list(inspection.warnings)
    changes: list[PlannedFileChange] = []

    if inspection.configuration_mode == "missing":
        warnings.append("No configuration.nix or flake.nix entrypoint was found.")
        return _finalize_plan(
            status="blocked", inspection=inspection, changes=changes, warnings=warnings
        )

    if inspection.managed_status == "connected":
        if inspection.state_status in {"missing", "invalid"} or not inspection.migration:
            warnings.append(
                "The connected managed module has no safely readable state; automatic migration is blocked."
            )
            return _finalize_plan(
                status="blocked", inspection=inspection, changes=changes, warnings=warnings
            )
        assert inspection.managed_path is not None
        default_path = inspection.managed_path / "default.nix"
        output_path = _managed_output_from_default(default_path)
        if output_path is None:
            warnings.append(
                "The connected default.nix does not import managed.nix or packages.nix; manual review is required."
            )
            return _finalize_plan(
                status="manual", inspection=inspection, changes=changes, warnings=warnings
            )
        state_change = _file_change(
            root,
            inspection.state_path or inspection.managed_path / "state.json",
            serialize_state(inspection.migration.state),
            "Normalize the versioned UI state",
        )
        module_change = _file_change(
            root,
            output_path,
            generate_module(inspection.migration.state),
            "Regenerate the managed package module from normalized state",
        )
        changes.extend(change for change in (state_change, module_change) if change)
        status = (
            "migration-ready"
            if inspection.migration.requires_migration
            else ("ready" if changes else "no-changes")
        )
        return _finalize_plan(
            status=status, inspection=inspection, changes=changes, warnings=warnings
        )

    managed_path = inspection.managed_path or root / "ncm"
    if inspection.managed_status == "present-not-imported":
        warnings.append(
            "A managed directory already exists but is not imported; its files will not be overwritten automatically."
        )
        return _finalize_plan(
            status="manual", inspection=inspection, changes=changes, warnings=warnings
        )

    default_path = managed_path / "default.nix"
    output_path = managed_path / "managed.nix"
    state_path = managed_path / "state.json"
    empty_state = ManagedState.empty()
    for change in (
        _file_change(
            root,
            default_path,
            _standard_default_module(output_path.name),
            "Create a stable managed-module entrypoint",
        ),
        _file_change(
            root,
            output_path,
            generate_module(empty_state),
            "Create the generated NixOS settings module",
        ),
        _file_change(
            root,
            state_path,
            serialize_state(empty_state),
            "Create the versioned UI state",
        ),
    ):
        if change:
            changes.append(change)

    if inspection.managed_status != "import-missing":
        configuration_path = root / "configuration.nix"
        if not configuration_path.is_file():
            warnings.append(
                "No configuration.nix is available for a conservative import insertion."
            )
            return _finalize_plan(
                status="manual", inspection=inspection, changes=changes, warnings=warnings
            )
        candidate, warning = _insert_managed_import(configuration_path)
        if candidate is None:
            if warning:
                warnings.append(warning)
            return _finalize_plan(
                status="manual", inspection=inspection, changes=changes, warnings=warnings
            )
        config_change = _file_change(
            root,
            configuration_path,
            candidate,
            "Import the isolated Nix Control Manager module",
        )
        if config_change:
            changes.insert(0, config_change)

    return _finalize_plan(
        status="ready", inspection=inspection, changes=changes, warnings=warnings
    )
