from __future__ import annotations

from difflib import unified_diff
from pathlib import Path
from typing import Iterable

from .errors import ValidationError
from .nix_generator import render_value
from .storage import read_text_if_exists
from .user_model import UserManagedState, UserProfileState, validate_user_name


GENERATED_HOME_HEADER = """# Generated by Nix Control Manager. DO NOT EDIT BY HAND.
# Import this file from exactly one Home Manager profile.
# Nix Control Manager currently generates previews only and never writes this file.
"""


def generate_home_module(profile: UserProfileState) -> str:
    """Render one integration-agnostic Home Manager module."""

    lines = [GENERATED_HOME_HEADER.rstrip(), "", "{ pkgs, ... }:", "", "{"]
    if profile.packages:
        lines.append("  home.packages = [")
        lines.extend(f"    pkgs.{package}" for package in profile.packages)
        lines.append("  ];")

    if profile.packages and profile.options:
        lines.append("")

    for option_path, value in profile.options.items():
        rendered = render_value(value, indent=2)
        continuation = rendered.replace("\n", "\n  ")
        lines.append(f"  {option_path} = {continuation};")

    if not profile.packages and not profile.options:
        lines.append("  # No user settings are managed yet.")

    lines.extend(["}", ""])
    return "\n".join(lines)


def candidate_user_state(
    existing: UserManagedState,
    *,
    username: str,
    integration: str,
    packages: Iterable[str],
) -> UserManagedState:
    """Project a package edit while preserving every unrelated user and option."""

    previous = existing.users.get(username)
    options = dict(previous.options) if previous is not None else {}
    profile = UserProfileState.from_mapping(
        username,
        {
            "integration": integration,
            "packages": list(packages),
            "options": options,
        },
    )
    users = dict(existing.users)
    users[username] = profile
    return UserManagedState(schema_version=existing.schema_version, users=users)


def user_module_path(user_state_path: Path, username: str) -> Path:
    """Return the fixed future module path after validating the user name."""

    validate_user_name(username)
    return user_state_path.resolve().parent / f"managed-home-{username}.nix"


def build_home_preview(
    state: UserManagedState,
    *,
    username: str,
    output_path: Path,
) -> dict[str, object]:
    profile = state.users.get(username)
    if profile is None:
        raise ValidationError(f"Managed user {username!r} is missing from user-state")
    previous = read_text_if_exists(output_path)
    generated = generate_home_module(profile)
    diff = "".join(
        unified_diff(
            previous.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=output_path.name,
            tofile=f"{output_path.name} (candidate)",
        )
    )
    return {
        "username": username,
        "integration": profile.integration,
        "outputPath": str(output_path),
        "state": state.to_mapping(),
        "generated": generated,
        "diff": diff,
        "readOnly": True,
        "writeEnabled": False,
        "activationEnabled": False,
        "flakeInputMutationEnabled": False,
    }
