from __future__ import annotations

import re
from typing import Any, Mapping

from .errors import ValidationError
from .model import ManagedState


GENERATED_HEADER = """# Generated by Nix Control Manager. DO NOT EDIT BY HAND.
# Edit the Nix Control Manager state or use its interface, then regenerate.
"""
_SIMPLE_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_'-]*$")


def _nix_string(value: str) -> str:
    for character in value:
        if ord(character) < 32 and character not in "\n\r\t":
            raise ValidationError("Strings cannot contain unsupported control characters")
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("${", "\\${")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _nix_key(value: str) -> str:
    return value if _SIMPLE_KEY.fullmatch(value) else _nix_string(value)


def render_value(value: Any, *, indent: int = 0) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            raise ValidationError("Nix cannot render a non-finite number")
        return repr(value)
    if isinstance(value, str):
        return _nix_string(value)
    if isinstance(value, list):
        if not value:
            return "[ ]"
        prefix = " " * indent
        child = " " * (indent + 2)
        rendered = "\n".join(
            f"{child}{render_value(item, indent=indent + 2)}" for item in value
        )
        return f"[\n{rendered}\n{prefix}]"
    if isinstance(value, Mapping):
        if not value:
            return "{ }"
        prefix = " " * indent
        child = " " * (indent + 2)
        rendered = "\n".join(
            f"{child}{_nix_key(str(key))} = {render_value(item, indent=indent + 2)};"
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        )
        return f"{{\n{rendered}\n{prefix}}}"
    raise ValidationError(f"Cannot render value of type {type(value).__name__}")


def generate_module(state: ManagedState) -> str:
    lines = [GENERATED_HEADER.rstrip(), "", "{ pkgs, ... }:", "", "{"]

    if state.packages:
        lines.append("  environment.systemPackages = [")
        lines.extend(f"    pkgs.{package}" for package in state.packages)
        lines.append("  ];")

    if state.packages and state.options:
        lines.append("")

    for option_path, value in state.options.items():
        rendered = render_value(value, indent=2)
        if "\n" in rendered:
            continuation = rendered.replace("\n", "\n  ")
            lines.append(f"  {option_path} = {continuation};")
        else:
            lines.append(f"  {option_path} = {rendered};")

    if not state.packages and not state.options:
        lines.append("  # No settings are managed yet.")

    lines.extend(["}", ""])
    return "\n".join(lines)
