from pathlib import Path
import tempfile
import threading
import time
import unittest

from nix_control_manager.candidate_build import (
    BuildPreviewError,
    CandidateBuildManager,
)


class CandidateBuildManagerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name) / "etc-nixos"
        self.root.mkdir()

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def create_connected_legacy_configuration(self) -> None:
        (self.root / "configuration.nix").write_text(
            "{ ... }: {\n  imports = [\n    ./ncm\n  ];\n}\n", encoding="utf-8"
        )
        managed = self.root / "ncm"
        managed.mkdir()
        (managed / "default.nix").write_text(
            "{ ... }: { imports = [ ./packages.nix ]; }\n", encoding="utf-8"
        )
        (managed / "packages.nix").write_text(
            "{ pkgs, ... }: { environment.systemPackages = with pkgs; [ ]; }\n",
            encoding="utf-8",
        )
        (managed / "state.json").write_text(
            '{"schemaVersion":1,"packages":{},"options":{}}', encoding="utf-8"
        )

    @staticmethod
    def fake_which(name: str) -> str:
        return f"/tools/{name}"

    @staticmethod
    def wait_for_terminal(manager: CandidateBuildManager, job_id: str) -> dict:
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            result = manager.poll(job_id)
            if not result["cancellable"]:
                return result
            time.sleep(0.01)
        raise AssertionError("build-preview job did not finish")

    def test_channel_build_uses_disposable_copy_and_fixed_unprivileged_argv(self) -> None:
        self.create_connected_legacy_configuration()
        source = (self.root / "ncm" / "packages.nix").read_text(encoding="utf-8")
        candidate_directories: list[Path] = []

        def executor(command, cwd, cancel_event, line_sink):
            candidate_directories.append(cwd)
            self.assertNotEqual(cwd, self.root)
            self.assertIn(
                "Generated by Nix Control Manager",
                (cwd / "ncm" / "packages.nix").read_text(encoding="utf-8"),
            )
            self.assertFalse(cancel_event.is_set())
            line_sink("stderr", "building the system closure")
            output = "/nix/store/" + "a" * 32 + "-nixos-system-preview"
            line_sink("stdout", output)
            return 0, (output,)

        manager = CandidateBuildManager(
            config_root=self.root,
            executor=executor,
            which=self.fake_which,
            timeout=5,
        )
        started = manager.start()
        result = self.wait_for_terminal(manager, started["jobId"])
        manager.close()

        self.assertEqual(result["status"], "passed")
        self.assertEqual(result["command"][0], "/tools/nix-build")
        self.assertIn("--no-out-link", result["command"])
        self.assertNotIn("nixos-rebuild", " ".join(result["command"]))
        self.assertEqual(len(result["outputPaths"]), 1)
        self.assertTrue(result["workingCopyRemoved"])
        self.assertFalse(result["privileged"])
        self.assertFalse(result["configurationWriteEnabled"])
        self.assertFalse(result["activationEnabled"])
        self.assertTrue(result["nixStoreWriteExpected"])
        self.assertTrue(all(not path.exists() for path in candidate_directories))
        self.assertEqual(
            (self.root / "ncm" / "packages.nix").read_text(encoding="utf-8"),
            source,
        )
        self.assertTrue(any(event["stream"] == "stderr" for event in result["events"]))

    def test_flake_build_has_no_link_or_lock_file_write(self) -> None:
        (self.root / "flake.nix").write_text("{ outputs = _: { }; }\n", encoding="utf-8")
        (self.root / "configuration.nix").write_text(
            "{ ... }: {\n  imports = [\n  ];\n}\n", encoding="utf-8"
        )
        commands: list[tuple[str, ...]] = []

        def executor(command, cwd, cancel_event, line_sink):
            commands.append(tuple(command))
            return 0, ()

        manager = CandidateBuildManager(
            config_root=self.root,
            flake_target="desktop",
            executor=executor,
            which=self.fake_which,
        )
        started = manager.start()
        result = self.wait_for_terminal(manager, started["jobId"])
        manager.close()

        self.assertEqual(result["status"], "passed")
        command = commands[0]
        self.assertEqual(command[0], "/tools/nix")
        self.assertIn("build", command)
        self.assertIn("--no-link", command)
        self.assertIn("--print-out-paths", command)
        self.assertIn("--print-build-logs", command)
        self.assertIn("--no-write-lock-file", command)
        self.assertIn(
            ".#nixosConfigurations.desktop.config.system.build.toplevel", command
        )

    def test_successful_build_adds_fixed_unprivileged_closure_diff(self) -> None:
        self.create_connected_legacy_configuration()
        current_system = Path(self.temporary.name) / "current-system"
        current_system.mkdir()
        commands: list[tuple[str, ...]] = []

        def executor(command, cwd, cancel_event, line_sink):
            commands.append(tuple(command))
            if "diff-closures" in command:
                line_sink("stdout", "firefox: 1.0 → 2.0, +10.0 KiB")
                return 0, ("firefox: 1.0 → 2.0, +10.0 KiB",)
            output = "/nix/store/" + "c" * 32 + "-nixos-system-preview"
            line_sink("stdout", output)
            return 0, (output,)

        manager = CandidateBuildManager(
            config_root=self.root,
            executor=executor,
            which=self.fake_which,
            path_is_dir=lambda _: True,
            current_system_path=current_system,
        )
        started = manager.start()
        result = self.wait_for_terminal(manager, started["jobId"])
        manager.close()

        self.assertEqual(result["status"], "passed")
        self.assertTrue(result["impactAvailable"])
        self.assertIn("firefox", result["closureDiff"])
        impact = commands[1]
        self.assertEqual(impact[0], "/tools/nix")
        self.assertIn("diff-closures", impact)
        self.assertNotIn("nixos-rebuild", impact)
        self.assertFalse(result["dryActivateExecuted"])
        self.assertTrue(result["activationPreviewReady"])

    def test_cancel_stops_job_and_allows_a_later_build(self) -> None:
        self.create_connected_legacy_configuration()
        entered = threading.Event()

        def executor(command, cwd, cancel_event, line_sink):
            entered.set()
            line_sink("stderr", "long build started")
            self.assertTrue(cancel_event.wait(timeout=3))
            return 143, ()

        manager = CandidateBuildManager(
            config_root=self.root,
            executor=executor,
            which=self.fake_which,
        )
        first = manager.start()
        self.assertTrue(entered.wait(timeout=2))
        with self.assertRaises(BuildPreviewError):
            manager.start()
        cancelling = manager.cancel(first["jobId"])
        self.assertEqual(cancelling["status"], "cancelling")
        cancelled = self.wait_for_terminal(manager, first["jobId"])
        self.assertEqual(cancelled["status"], "cancelled")
        self.assertTrue(cancelled["workingCopyRemoved"])

        entered.clear()
        second = manager.start()
        self.assertNotEqual(second["jobId"], first["jobId"])
        self.assertTrue(entered.wait(timeout=2))
        manager.cancel(second["jobId"])
        self.wait_for_terminal(manager, second["jobId"])
        manager.close()

    def test_timeout_is_distinct_from_user_cancellation(self) -> None:
        self.create_connected_legacy_configuration()

        def executor(command, cwd, cancel_event, line_sink):
            self.assertTrue(cancel_event.wait(timeout=3))
            return 143, ()

        manager = CandidateBuildManager(
            config_root=self.root,
            timeout=1,
            executor=executor,
            which=self.fake_which,
        )
        started = manager.start()
        result = self.wait_for_terminal(manager, started["jobId"])
        manager.close()

        self.assertEqual(result["status"], "failed")
        self.assertTrue(result["timedOut"])
        self.assertEqual(result["error"]["code"], "build-timed-out")

    def test_unsafe_plan_and_missing_nix_fail_closed(self) -> None:
        blocked_manager = CandidateBuildManager(
            config_root=self.root,
            executor=lambda *args: self.fail("executor must not run"),
            which=self.fake_which,
        )
        blocked = blocked_manager.start()
        blocked = self.wait_for_terminal(blocked_manager, blocked["jobId"])
        self.assertEqual(blocked["status"], "blocked")
        self.assertFalse(blocked["configurationWriteEnabled"])
        blocked_manager.close()

        self.create_connected_legacy_configuration()
        unavailable_manager = CandidateBuildManager(
            config_root=self.root,
            executor=lambda *args: self.fail("executor must not run"),
            which=lambda _: None,
        )
        unavailable = unavailable_manager.start()
        unavailable = self.wait_for_terminal(
            unavailable_manager, unavailable["jobId"]
        )
        self.assertEqual(unavailable["status"], "unavailable")
        unavailable_manager.close()

    def test_effective_root_is_rejected_before_plan_or_process_execution(self) -> None:
        self.create_connected_legacy_configuration()
        manager = CandidateBuildManager(
            config_root=self.root,
            executor=lambda *args: self.fail("executor must not run as root"),
            which=self.fake_which,
            effective_uid=lambda: 0,
        )
        started = manager.start()
        result = self.wait_for_terminal(manager, started["jobId"])
        manager.close()

        self.assertEqual(result["status"], "blocked")
        self.assertTrue(result["privileged"])
        self.assertEqual(result["effectiveUid"], 0)
        self.assertEqual(result["error"]["code"], "privileged-execution")


if __name__ == "__main__":
    unittest.main()
