from dataclasses import replace
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

from nix_control_manager.adoption import plan_adoption
from nix_control_manager.candidate import validate_adoption
from nix_control_manager.errors import TransactionError
from nix_control_manager.transaction import (
    SimulatedTransactionCrash,
    apply_plan_in_fixture,
    finalize_fixture_transaction,
    initialize_transaction_fixture,
    recover_pending_fixture_transactions,
    rollback_fixture_transaction,
)


class FixtureTransactionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        temporary = Path(self.temporary.name)
        self.root = temporary / "configuration-root"
        self.journal = temporary / "journals"
        initialize_transaction_fixture(self.root)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    @staticmethod
    def fake_which(name: str) -> str:
        return f"/tools/{name}"

    @staticmethod
    def fake_runner(command, **kwargs):
        return subprocess.CompletedProcess(command, 0, "/nix/store/fake.drv\n", "")

    def validate(self):
        return validate_adoption(
            self.root,
            runner=self.fake_runner,
            which=self.fake_which,
        )

    def create_legacy_configuration(self) -> None:
        (self.root / "configuration.nix").write_text(
            "{ ... }: {\n  imports = [\n    ./ncm\n  ];\n}\n", encoding="utf-8"
        )
        managed = self.root / "ncm"
        managed.mkdir()
        (managed / "default.nix").write_text(
            "{ ... }: { imports = [ ./packages.nix ]; }\n", encoding="utf-8"
        )
        (managed / "packages.nix").write_text(
            "{ pkgs, ... }: { environment.systemPackages = with pkgs; [ ]; }\n",
            encoding="utf-8",
        )
        (managed / "state.json").write_text(
            '{"schemaVersion":1,"nixosRelease":"26.05","packages":{},"options":{}}',
            encoding="utf-8",
        )

    def create_fresh_configuration(self) -> str:
        original = (
            "{ ... }:\n\n{\n  imports = [\n"
            "    ./hardware-configuration.nix\n  ];\n}\n"
        )
        (self.root / "configuration.nix").write_text(original, encoding="utf-8")
        (self.root / "hardware-configuration.nix").write_text(
            "{ ... }: { }\n", encoding="utf-8"
        )
        return original

    def only_manifest(self) -> Path:
        manifests = list(self.journal.glob("*/manifest.json"))
        self.assertEqual(len(manifests), 1)
        return manifests[0]

    def test_provisional_commit_retains_verified_backups_and_awaits_evaluation(self) -> None:
        self.create_legacy_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        previous_state = (self.root / "ncm" / "state.json").read_bytes()
        previous_module = (self.root / "ncm" / "packages.nix").read_bytes()

        result = apply_plan_in_fixture(plan, validation, journal_root=self.journal)

        self.assertEqual(result.state, "awaiting-verification")
        self.assertFalse(result.to_mapping()["activationEnabled"])
        normalized = json.loads((self.root / "ncm" / "state.json").read_text(encoding="utf-8"))
        self.assertEqual(normalized, {"options": {}, "packages": [], "schemaVersion": 1})
        self.assertIn(
            "Generated by Nix Control Manager",
            (self.root / "ncm" / "packages.nix").read_text(encoding="utf-8"),
        )
        manifest = json.loads(result.journal_path.read_text(encoding="utf-8"))
        self.assertEqual(manifest["state"], "awaiting-verification")
        self.assertEqual(manifest["planFingerprint"], validation.plan_fingerprint)
        self.assertEqual(
            (result.journal_path.parent / "backups" / "0000.bin").read_bytes(),
            previous_state,
        )
        self.assertEqual(
            (result.journal_path.parent / "backups" / "0001.bin").read_bytes(),
            previous_module,
        )

    @unittest.skipIf(os.name == "nt", "POSIX directory modes are required")
    def test_created_configuration_directories_override_a_restrictive_umask(self) -> None:
        self.create_fresh_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        previous_umask = os.umask(0o077)
        try:
            apply_plan_in_fixture(plan, validation, journal_root=self.journal)
        finally:
            os.umask(previous_umask)

        self.assertEqual((self.root / "ncm").stat().st_mode & 0o777, 0o755)
        self.assertEqual(
            (self.root / "ncm" / "default.nix").stat().st_mode & 0o777,
            0o644,
        )

    def test_rejects_concurrent_edit_before_any_write(self) -> None:
        self.create_legacy_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        state_before = (self.root / "ncm" / "state.json").read_bytes()
        (self.root / "ncm" / "packages.nix").write_text("# external edit\n", encoding="utf-8")

        with self.assertRaisesRegex(TransactionError, "Concurrent edit"):
            apply_plan_in_fixture(plan, validation, journal_root=self.journal)

        self.assertEqual((self.root / "ncm" / "state.json").read_bytes(), state_before)
        self.assertEqual(
            (self.root / "ncm" / "packages.nix").read_text(encoding="utf-8"),
            "# external edit\n",
        )
        self.assertFalse(self.journal.exists())

    def test_finalize_rejects_validation_that_still_proposes_candidate_files(self) -> None:
        self.create_legacy_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        original_state = (self.root / "ncm" / "state.json").read_bytes()
        provisional = apply_plan_in_fixture(
            plan, validation, journal_root=self.journal
        )

        with self.assertRaisesRegex(TransactionError, "additional changes"):
            finalize_fixture_transaction(
                self.root,
                journal_root=self.journal,
                transaction_id=provisional.transaction_id,
                verification=validation,
            )

        rollback_fixture_transaction(
            self.root,
            journal_root=self.journal,
            transaction_id=provisional.transaction_id,
            reason="test cleanup after rejected finalize",
        )
        self.assertEqual((self.root / "ncm" / "state.json").read_bytes(), original_state)

    def test_injected_partial_failure_rolls_back_files_and_created_directories(self) -> None:
        original = self.create_fresh_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()

        with self.assertRaisesRegex(TransactionError, "was rolled back"):
            apply_plan_in_fixture(
                plan,
                validation,
                journal_root=self.journal,
                fault_after_commits=2,
            )

        self.assertEqual(
            (self.root / "configuration.nix").read_text(encoding="utf-8"), original
        )
        self.assertFalse((self.root / "ncm").exists())
        manifest = json.loads(self.only_manifest().read_text(encoding="utf-8"))
        self.assertEqual(manifest["state"], "rolled-back")
        self.assertTrue(all(entry["status"] == "rolled-back" for entry in manifest["changes"][:2]))

    def test_simulated_crash_is_recovered_from_the_journal(self) -> None:
        original = self.create_fresh_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()

        with self.assertRaises(SimulatedTransactionCrash):
            apply_plan_in_fixture(
                plan,
                validation,
                journal_root=self.journal,
                fault_after_commits=2,
                simulate_crash=True,
            )
        self.assertIn("./ncm", (self.root / "configuration.nix").read_text(encoding="utf-8"))
        self.assertTrue((self.root / "ncm" / "default.nix").exists())

        recovered = recover_pending_fixture_transactions(
            self.root, journal_root=self.journal
        )

        self.assertEqual(len(recovered), 1)
        self.assertEqual(recovered[0].state, "recovered")
        self.assertEqual(
            (self.root / "configuration.nix").read_text(encoding="utf-8"), original
        )
        self.assertFalse((self.root / "ncm").exists())
        manifest = json.loads(self.only_manifest().read_text(encoding="utf-8"))
        self.assertEqual(manifest["state"], "recovered")

    def test_recovery_refuses_to_overwrite_a_post_crash_external_edit(self) -> None:
        self.create_fresh_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        with self.assertRaises(SimulatedTransactionCrash):
            apply_plan_in_fixture(
                plan,
                validation,
                journal_root=self.journal,
                fault_after_commits=1,
                simulate_crash=True,
            )
        (self.root / "configuration.nix").write_text("# changed after crash\n", encoding="utf-8")

        with self.assertRaisesRegex(TransactionError, "manual attention"):
            recover_pending_fixture_transactions(self.root, journal_root=self.journal)

        self.assertEqual(
            (self.root / "configuration.nix").read_text(encoding="utf-8"),
            "# changed after crash\n",
        )
        manifest = json.loads(self.only_manifest().read_text(encoding="utf-8"))
        self.assertEqual(manifest["state"], "recovery-required")

    def test_rejects_a_changed_validation_fingerprint(self) -> None:
        self.create_legacy_configuration()
        plan = plan_adoption(self.root)
        validation = replace(self.validate(), plan_fingerprint="0" * 64)
        original = (self.root / "ncm" / "state.json").read_bytes()

        with self.assertRaisesRegex(TransactionError, "fingerprint"):
            apply_plan_in_fixture(plan, validation, journal_root=self.journal)

        self.assertEqual((self.root / "ncm" / "state.json").read_bytes(), original)
        self.assertFalse(self.journal.exists())

    def test_apply_requires_the_exact_fixture_marker(self) -> None:
        self.create_legacy_configuration()
        plan = plan_adoption(self.root)
        validation = self.validate()
        (self.root / ".ncm-transaction-fixture").unlink()

        with self.assertRaisesRegex(TransactionError, "Fixture marker"):
            apply_plan_in_fixture(plan, validation, journal_root=self.journal)

        self.assertFalse(self.journal.exists())

    def test_fixture_initializer_refuses_any_path_shaped_like_live_nixos(self) -> None:
        live_shaped = Path(self.temporary.name) / "fake" / "etc" / "nixos"

        with self.assertRaisesRegex(TransactionError, "refuses /etc/nixos"):
            initialize_transaction_fixture(live_shaped)

        self.assertFalse(live_shaped.exists())


if __name__ == "__main__":
    unittest.main()
