from pathlib import Path
import tempfile
import unittest

from nix_control_manager.home_manager_generator import (
    build_home_preview,
    candidate_user_state,
    generate_home_module,
    user_module_path,
)
from nix_control_manager.user_model import UserManagedState, UserProfileState


class HomeManagerGeneratorTests(unittest.TestCase):
    def test_generates_deterministic_integration_agnostic_module(self) -> None:
        profile = UserProfileState.from_mapping(
            "alice",
            {
                "integration": "nixos-module",
                "packages": ["vlc", "firefox"],
                "options": {"programs.git.enable": True},
            },
        )
        self.assertEqual(
            generate_home_module(profile),
            """# Generated by Nix Control Manager. DO NOT EDIT BY HAND.
# Import this file from exactly one Home Manager profile.
# Nix Control Manager currently generates previews only and never writes this file.

{ pkgs, ... }:

{
  home.packages = [
    pkgs.firefox
    pkgs.vlc
  ];

  programs.git.enable = true;
}
""",
        )

    def test_candidate_preserves_other_users_and_existing_options(self) -> None:
        existing = UserManagedState.from_mapping(
            {
                "users": {
                    "alice": {
                        "integration": "nixos-module",
                        "packages": ["git"],
                        "options": {"programs.git.enable": True},
                    },
                    "bob": {
                        "integration": "standalone",
                        "packages": ["htop"],
                        "options": {},
                    },
                }
            }
        )
        candidate = candidate_user_state(
            existing,
            username="alice",
            integration="nixos-module",
            packages=["firefox"],
        )
        self.assertEqual(candidate.users["alice"].packages, ("firefox",))
        self.assertTrue(candidate.users["alice"].options["programs.git.enable"])
        self.assertEqual(candidate.users["bob"], existing.users["bob"])

    def test_preview_reads_existing_module_but_writes_nothing(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            state_path = root / "user-state.json"
            output = user_module_path(state_path, "alice")
            output.write_text("# previous\n", encoding="utf-8")
            state = candidate_user_state(
                UserManagedState.empty(),
                username="alice",
                integration="standalone",
                packages=["firefox"],
            )
            preview = build_home_preview(state, username="alice", output_path=output)
            self.assertIn("-# previous", preview["diff"])
            self.assertIn("home.packages", preview["generated"])
            self.assertEqual(output.read_text(encoding="utf-8"), "# previous\n")
            self.assertFalse(preview["writeEnabled"])
            self.assertFalse(preview["activationEnabled"])


if __name__ == "__main__":
    unittest.main()
