from pathlib import Path
import subprocess
import tempfile
import unittest

from nix_control_manager.candidate import validate_adoption


class CandidateValidationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name) / "etc-nixos"
        self.root.mkdir()

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def create_connected_legacy_configuration(self) -> None:
        (self.root / "configuration.nix").write_text(
            "{ ... }: {\n  imports = [\n    ./ncm\n  ];\n}\n", encoding="utf-8"
        )
        managed = self.root / "ncm"
        managed.mkdir()
        (managed / "default.nix").write_text(
            "{ ... }: { imports = [ ./packages.nix ]; }\n", encoding="utf-8"
        )
        (managed / "packages.nix").write_text(
            "{ pkgs, ... }: { environment.systemPackages = with pkgs; [ ]; }\n",
            encoding="utf-8",
        )
        (managed / "state.json").write_text(
            '{"schemaVersion":1,"packages":{},"options":{}}', encoding="utf-8"
        )

    @staticmethod
    def fake_which(name: str) -> str:
        return f"/tools/{name}"

    def test_materializes_evaluates_and_removes_disposable_candidate(self) -> None:
        self.create_connected_legacy_configuration()
        working_directories: list[Path] = []

        def runner(command, **kwargs):
            cwd = Path(kwargs["cwd"])
            working_directories.append(cwd)
            self.assertNotEqual(cwd, self.root)
            generated = (cwd / "ncm" / "packages.nix").read_text(encoding="utf-8")
            self.assertIn("Generated by Nix Control Manager", generated)
            return subprocess.CompletedProcess(command, 0, "/nix/store/fake.drv\n", "")

        result = validate_adoption(
            self.root, timeout=5, runner=runner, which=self.fake_which
        )

        self.assertEqual(result.status, "passed")
        self.assertTrue(result.ready_for_apply_protocol)
        self.assertFalse(result.to_mapping()["activationEnabled"])
        self.assertEqual(len(result.plan_fingerprint or ""), 64)
        self.assertEqual(
            set(dict(result.candidate_digests)), {"ncm/state.json", "ncm/packages.nix"}
        )
        self.assertEqual(len(result.checks), 2)
        self.assertEqual(result.checks[-1].name, "Evaluate NixOS system derivation")
        self.assertTrue(working_directories)
        self.assertTrue(all(not path.exists() for path in working_directories))
        original = (self.root / "ncm" / "packages.nix").read_text(encoding="utf-8")
        self.assertNotIn("Generated by Nix Control Manager", original)

    def test_stops_after_failed_parse(self) -> None:
        self.create_connected_legacy_configuration()
        calls = 0

        def runner(command, **kwargs):
            nonlocal calls
            calls += 1
            return subprocess.CompletedProcess(command, 1, "", "syntax error")

        result = validate_adoption(self.root, runner=runner, which=self.fake_which)

        self.assertEqual(result.status, "failed")
        self.assertFalse(result.ready_for_apply_protocol)
        self.assertEqual(calls, 1)
        self.assertEqual(result.checks[0].status, "failed")
        self.assertIn("syntax error", result.checks[0].stderr)

    def test_reports_unavailable_nix_without_creating_a_candidate(self) -> None:
        self.create_connected_legacy_configuration()

        result = validate_adoption(self.root, which=lambda _: None)

        self.assertEqual(result.status, "unavailable")
        self.assertEqual(result.checks, ())
        self.assertTrue(any("nix-instantiate" in item for item in result.warnings))

    def test_flake_validation_uses_explicit_host_target(self) -> None:
        (self.root / "flake.nix").write_text("{ outputs = _: { }; }\n", encoding="utf-8")
        (self.root / "configuration.nix").write_text(
            "{ ... }: {\n  imports = [\n  ];\n}\n", encoding="utf-8"
        )
        commands: list[list[str]] = []

        def runner(command, **kwargs):
            commands.append(command)
            return subprocess.CompletedProcess(command, 0, "/nix/store/fake.drv", "")

        result = validate_adoption(
            self.root,
            flake_target="desktop",
            runner=runner,
            which=self.fake_which,
        )

        self.assertEqual(result.status, "passed")
        self.assertEqual(result.flake_target, "desktop")
        self.assertIn(
            ".#nixosConfigurations.desktop.config.system.build.toplevel.drvPath",
            commands[-1],
        )
        self.assertIn("--no-write-lock-file", commands[-1])


if __name__ == "__main__":
    unittest.main()
