import unittest

from nix_control_manager.model import ManagedState
from nix_control_manager.nix_generator import generate_module, render_value


class GeneratorTests(unittest.TestCase):
    def test_generates_deterministic_module(self) -> None:
        state = ManagedState.from_mapping(
            {
                "packages": ["vlc", "firefox"],
                "options": {
                    "networking.hostName": "nixbox",
                    "programs.steam.enable": True,
                },
            }
        )

        self.assertEqual(
            generate_module(state),
            """# Generated by Nix Control Manager. DO NOT EDIT BY HAND.
# Edit the Nix Control Manager state or use its interface, then regenerate.

{ pkgs, ... }:

{
  environment.systemPackages = [
    pkgs.firefox
    pkgs.vlc
  ];

  networking.hostName = "nixbox";
  programs.steam.enable = true;
}
""",
        )

    def test_escapes_nix_interpolation(self) -> None:
        self.assertEqual(render_value("hello ${builtins.abort}"), '"hello \\${builtins.abort}"')

    def test_renders_nested_json_values(self) -> None:
        rendered = render_value({"enabled": True, "ports": [80, 443]})
        self.assertIn("enabled = true;", rendered)
        self.assertIn("ports = [", rendered)

    def test_empty_state_is_a_valid_module(self) -> None:
        generated = generate_module(ManagedState.empty())
        self.assertIn("{ pkgs, ... }:", generated)
        self.assertIn("# No settings are managed yet.", generated)


if __name__ == "__main__":
    unittest.main()
