{ pkgs, ncmPackage, ncmModule }:

let
  socketPath = "/run/nix-control-manager/helper.sock";
  journalRoot = "/var/lib/nix-control-manager/managed-transactions";
  client = "${ncmPackage}/bin/ncm-helper-client --socket ${socketPath} --timeout 300";
  runAs = user: "${pkgs.util-linux}/bin/runuser -u ${user} --";
in
pkgs.testers.runNixOSTest {
  name = "nix-control-manager-live-managed";

  nodes.machine = { pkgs, ... }: {
    imports = [ ncmModule ];
    virtualisation.memorySize = 2048;
    virtualisation.writableStore = true;
    nix.nixPath = [ "nixpkgs=${pkgs.path}" ];

    users.users.managed-denied.isNormalUser = true;
    users.users.managed-authorized.isNormalUser = true;
    environment.systemPackages = [ ncmPackage pkgs.jq ];

    services.nix-control-manager-helper = {
      enable = true;
      mode = "live-managed";
      targetId = "managed";
      managedJournalRoot = journalRoot;
      allowedUsers = [ "managed-denied" "managed-authorized" ];
      validationTimeout = 300;
    };

    security.polkit.extraConfig = ''
      // Test-only authorization inside the disposable VM.
      polkit.addRule(function(action, subject) {
        if (action.id == "org.nixos.nix-control-manager.apply-validated-managed-plan" &&
            subject.user == "managed-authorized") {
          return polkit.Result.YES;
        }
      });
    '';

    systemd.services.ncm-live-managed-setup = {
      description = "Prepare disposable NCM-owned NixOS sources";
      wantedBy = [ "multi-user.target" ];
      before = [ "nix-control-manager-helper.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        install -d -m 0755 /etc/nixos/ncm
        cat > /etc/nixos/configuration.nix <<'EOF'
        { ... }:
        {
          imports = [ ./ncm ];
          boot.isContainer = true;
          system.stateVersion = "26.05";
        }
        EOF
        cat > /etc/nixos/ncm/default.nix <<'EOF'
        { ... }:
        {
          imports = [ ./packages.nix ];
        }
        EOF
        cat > /etc/nixos/ncm/state.json <<'EOF'
        {
          "options": {},
          "packages": [],
          "schemaVersion": 1
        }
        EOF
        cat > /etc/nixos/ncm/packages.nix <<'EOF'
        # Generated by Nix Control Manager. DO NOT EDIT BY HAND.
        # Edit the Nix Control Manager state or use its interface, then regenerate.

        { pkgs, ... }:

        {
          # No settings are managed yet.
        }
        EOF
        cat > /tmp/managed-state.json <<'EOF'
        {
          "schemaVersion": 1,
          "packages": ["git"],
          "options": {}
        }
        EOF
        chmod 0644 /etc/nixos/configuration.nix /etc/nixos/ncm/*.nix \
          /etc/nixos/ncm/state.json /tmp/managed-state.json
      '';
    };
    systemd.services.nix-control-manager-helper = {
      requires = [ "ncm-live-managed-setup.service" ];
      after = [ "ncm-live-managed-setup.service" ];
    };
  };

  testScript = ''
    from datetime import timedelta
    import json

    timeout = timedelta(seconds=300)
    machine.start()
    machine.wait_for_unit("multi-user.target")
    machine.wait_for_unit("ncm-live-managed-setup.service")
    machine.wait_for_unit("nix-control-manager-helper.socket")

    capabilities = json.loads(machine.succeed(
        "${runAs "managed-denied"} ${client} capabilities"
    ))
    target = capabilities["result"]["targets"][0]
    t.assertTrue(target["liveTarget"])
    t.assertTrue(target["readOnly"])
    t.assertFalse(target["applyEnabled"])
    t.assertTrue(target["managedWriteEnabled"])
    t.assertTrue(target["managedRecoveryEnabled"])
    t.assertFalse(target["dryActivatePreviewEnabled"])
    t.assertEqual(
        sorted(target["allowedRelativePaths"]),
        ["ncm/packages.nix", "ncm/state.json"],
    )

    machine.wait_for_unit("nix-control-manager-helper.service")
    rw_paths = machine.succeed(
        "systemctl show nix-control-manager-helper.service -p ReadWritePaths --value"
    )
    t.assertIn("/etc/nixos/ncm", rw_paths)
    t.assertIn("${journalRoot}", rw_paths)
    t.assertNotIn("/etc/nixos ", rw_paths)
    t.assertEqual(
        machine.succeed(
            "systemctl show nix-control-manager-helper.service -p CapabilityBoundingSet --value"
        ).strip(),
        "",
    )

    config_hash = machine.succeed("sha256sum /etc/nixos/configuration.nix").split()[0]
    default_hash = machine.succeed("sha256sum /etc/nixos/ncm/default.nix").split()[0]
    current_system = machine.succeed("readlink -f /run/current-system").strip()

    denied_validation = json.loads(machine.succeed(
        "${runAs "managed-denied"} ${client} validate-managed-plan "
        "--target managed --config-root /etc/nixos --state /tmp/managed-state.json",
        timeout=timeout,
    ))["result"]
    denied_status, _ = machine.execute(
        "${runAs "managed-denied"} ${client} apply-managed-plan --target managed "
        f"--plan-fingerprint {denied_validation['planFingerprint']} "
        f"--receipt {denied_validation['validationReceipt']} > /tmp/denied.json",
        timeout=timeout,
    )
    t.assertEqual(denied_status, 2)
    t.assertEqual(json.loads(machine.succeed("cat /tmp/denied.json"))["status"], "denied")
    machine.succeed("jq -e '.packages == []' /etc/nixos/ncm/state.json")

    validated = json.loads(machine.succeed(
        "${runAs "managed-authorized"} ${client} validate-managed-plan "
        "--target managed --config-root /etc/nixos --state /tmp/managed-state.json",
        timeout=timeout,
    ))["result"]
    applied = json.loads(machine.succeed(
        "${runAs "managed-authorized"} ${client} apply-managed-plan --target managed "
        f"--plan-fingerprint {validated['planFingerprint']} "
        f"--receipt {validated['validationReceipt']}",
        timeout=timeout,
    ))["result"]
    t.assertEqual(applied["state"], "committed")
    t.assertEqual(applied["filesWritten"], 2)
    t.assertTrue(applied["managedWriteEnabled"])
    t.assertFalse(applied["activationEnabled"])
    t.assertFalse(applied["switchEnabled"])
    t.assertEqual(machine.succeed("readlink -f /run/current-system").strip(), current_system)
    t.assertEqual(machine.succeed("sha256sum /etc/nixos/configuration.nix").split()[0], config_hash)
    t.assertEqual(machine.succeed("sha256sum /etc/nixos/ncm/default.nix").split()[0], default_hash)
    machine.succeed("jq -e '.packages == [\"git\"]' /etc/nixos/ncm/state.json")
    machine.succeed("grep -F 'pkgs.git' /etc/nixos/ncm/packages.nix")
    machine.succeed("grep -R -F '\"transactionKind\": \"managed-state\"' ${journalRoot}/*/manifest.json")
    machine.succeed("grep -R -F '\"state\": \"committed\"' ${journalRoot}/*/manifest.json")
  '';
}
